services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/backend
      - ./images:/backend/images
    ports:
      - "8000:8000"
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: ng serve --host 0.0.0.0 --configuration development
    volumes:
      - ./frontend:/frontend
    ports:
      - "4200:4200"